### ISSUE TITLE
Fortran support

### ISSUE THREAD

**Issue by albertziegenhagel** [ninja-build/ninja#1265]
Currently there is a fork maintained by @bradking from Kitware that adds Fortran support to ninja.

Support in CMake to generate ninja files including Fortran has been present for quiet a while now and we are using the fork successfully for many projects in my company. It would be great if that work could be added to upstream ninja, so that we no longer need to rely on a fork.

There are two merge requests (#1039 and #1111) related to this topic that for some reason do not seem to get a lot of attention...

**Comment by janusw** [comment]
I have recently tried the fork at https://github.com/Kitware/ninja on a large Fortran project ( >300 kloc in over 800 files, mostly F90 with some F77) and it works absolutely great, without any flaws.

Also it finally makes cmake usable with Fortran by providing great performance improvements: The project mentioned above takes about 30s for a trivial (no-op) rebuild with cmake+make, while cmake+ninja does it in a split second.

I'ld really love to see the Fortran supported being merged into the official ninja repository.

**Comment by petsche** [comment]
My team has also been using the Kitware ninja fork for a large project that contains both C++ and Fortran without any flaws. It does seem like it is time for these merge requests to get attention. Thanks @bradking for the good work.

**Comment by janusw** [comment]
> There are two merge requests (#1039 and #1111) related to this topic

Apparently the latter is merged by now, so we're halfway there and only #1039 is still missing ...

**Comment by bradking** [comment]
The next step is #1294.

**Comment by mathomp4** [comment]
@bradking I haven't seen any new updates to [Kitware/ninja](https://github.com/Kitware/ninja) in a while (2017 Jun 21). Does ninja now support Fortran in such a way that I can use the canonical ninja? (I thought about asking on the Kitware/ninja issues...but there are none.)

**Comment by mathstuf** [comment]
@mathomp4 PR #1294 is waiting for canonical Ninja to support Fortran (I don't know how many steps are left after it).

**Comment by mathomp4** [comment]
@mathstuf Ah. Okay. I just hadn't seen a new Kitware ninja, so I thought it might have gone moribund because it wasn't needed. :)

**Comment by mathstuf** [comment]
Nope, Fortran just doesn't change much these days ;) .

**Comment by janusw** [comment]
> I just hadn't seen a new Kitware ninja, so I thought it might have gone moribund because it wasn't needed. :)

ninja supporting Fortran is dearly needed, actually. I have used the branch on a regular basis for the last couple of months (both on Linux and Windows), and it really works great. I sincerely hope this will be merged into the ninja master very soon!

**Comment by janusw** [comment]
> Nope, Fortran just doesn't change much these days ;) .

Fortran as such? It does change: https://wg5-fortran.org/f2018.html  
Not sure that's what you meant, though ;-P

**Comment by octol** [comment]
Agree I've been checking this issue for months. I too use the kitware fork and it's been working great on both Windows and Linux. Would be fantastic to have this in master!

**Comment by nico** [comment]
I just merged #1294. My apologies to everyone I'm so slow in reviewing the fortran patches. Brad's doing a great job making them easy to review too.

**Comment by janusw** [comment]
@nico Great news, thank you! What's the next step towards full Fortran support for ninja? It seems that at least #1039 is still missing ...?

**Comment by bradking** [comment]
The next steps are refactoring-only changes in #1412, #1413, and #1414.

**Comment by janusw** [comment]
Thanks for the update!

I have to admit that my personal need for Fortran support in ninja has actually decreased a bit recently, due to the much-improved performance of no-op rebuilds with cmake + Unix Makefiles + Fortran in cmake 3.11. However, I do still have a couple of usage scenarios left for ninja + Fortran, for example on Windows.

Thanks again for your ongoing efforts here, @nico and @bradking!

**Comment by bradking** [comment]
Another step is #1424 which extends the test infrastructure in a way needed to test Fortran support.  I was reserving it until later but saw discussion in another MR about possible conflicting changes.

**Comment by janusw** [comment]
It seems that #1039 has finally been merged. Still missing are #1414 and #1424 (at least) ...

**Comment by jhasse** [comment]
I've closed both as bradking is currently working on a bigger PR which adds the dyndep feature as a whole.

**Comment by loumalouomega** [comment]
Just one question, if I were interested in create a fork where to put all is need to compile with Fortran , which branches/PR should I consider right now?

**Comment by mathstuf** [comment]
@loumalouomega Already done: https://github.com/Kitware/ninja The default branch on that fork is `features-for-fortran`.

**Comment by loumalouomega** [comment]
Thanks a lot, I will take a look

**Comment by loumalouomega** [comment]
Nice :D
